services:
  gencut-frontend:
    build: ./services/cutdown-generator
    container_name: gencut-frontend
    expose:
      - "5679"
    volumes:
      - videos_data:/app/videos
      - ./videos/uploads:/app/videos/uploads
      - ./videos/cutdowns:/app/videos/cutdowns
      - ./static:/app/static
      - ./temp:/app/temp
      - ./templates:/app/templates
      - ./shared:/app/shared
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV:-production}
      - DEBUG=${DEBUG:-false}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    networks:
      - n8n-network
      - video-network
    restart: unless-stopped

  revoice:
    build: ./services/revoice
    container_name: revoice
    ports:
      - "5682:5679"
    volumes:
      - videos_data:/app/videos
      - ./temp:/app/temp
      - ./shared:/app/shared
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV:-production}
      - DEBUG=${DEBUG:-false}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    networks:
      - n8n-network
    restart: unless-stopped

  analyzer:
    build: ./services/analyzer
    ports:
      - "8000:8000"
    volumes:
      - videos_data:/app/videos
      - ./videos/uploads:/app/videos/uploads
      - ./videos/cutdowns:/app/videos/cutdowns
      - ./videos/separated:/app/videos/separated
    networks:
      - n8n-network
      - video-network
    restart: unless-stopped

  whisper:
    build: ./services/whisper
    container_name: whisper
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
      - ASR_DEVICE=cpu
      - ASR_COMPUTE_TYPE=int8
      - ASR_BATCH_SIZE=1
      - ASR_DOWNLOAD_ROOT=/app/asr_models
    volumes:
      - ./models:/app/asr_models
    networks:
      - video-network
      - n8n-network
    restart: unless-stopped

  imagebind-embed:
    build: ../imagebind-video-embed
    container_name: imagebind-embed
    ports:
      - "8750:8750"
    environment:
      - IMAGEBIND_WEIGHTS=/app/imagebind_huge.pth
      - OUTPUT_DIR=/app/outputs
    volumes:
      - videos_data:/data:ro
      - ./videos/embeddings:/app/outputs
    networks:
      - n8n-network
      - video-network
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: gencut-nginx
    ports:
      - "5679:5679"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
      - videos_data:/app/videos:ro
      - ./videos/uploads:/app/videos/uploads:ro
      - ./videos/cutdowns:/app/videos/cutdowns:ro
      - ./templates:/app/templates:ro
    depends_on:
      - gencut-frontend
    networks:
      - video-network
      - n8n-network
    restart: unless-stopped

  # storybook:
  #   build: ../component-library
  #   container_name: storybook
  #   ports:
  #     - "6006:6006"
  #   volumes:
  #     - ../component-library/src:/app/src
  #     - ../component-library/.storybook:/app/.storybook
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - n8n-network

volumes:
  static_data:
  videos_data:

networks:
  n8n-network:
    external: true
  video-network:
    external: true
